# Render Blueprint for PaperScope
# This file configures automatic deployments on Render.com
# See: https://render.com/docs/blueprint-spec

services:
  - type: web
    name: paperscope
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DEMO_MODE
        value: "1"
      - key: PYTHON_VERSION
        value: "3.11"
      - key: STREAMLIT_SERVER_PORT
        value: "8501"
      - key: STREAMLIT_SERVER_ADDRESS
        value: "0.0.0.0"
    healthCheckPath: /_stcore/health
    numInstances: 1
    plan: free
    region: oregon
    branch: main
    
  # Preview environments for pull requests
  # These are created automatically when PRs are opened
  # Each PR gets its own isolated environment
